export const CourseData = [
  {
    id: 1,
    teacher: "Aaron Powell",
    imageSrc: "/courses/course-1.jpg",
    teacherProfile: "/HomePageImages/admin-1.png",
    courseDetail:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "49.00",
    no_of_reviews: "14",
    priceBefore: "60.00",
    category: "Featured",
    Duration: "10 hours",
    Lectures: "6",
    Students: "Max 6",
    Video: "8 hours",
    SkillLevel: "Advanced",
    Language: "English",
    subratings: [
      "4",
      "5",
      "4",
      "3",
      "4",
      "5",
      "4",
      "3",
      "4",
      "4",
      "5",
      "3"
    ]
  },
  {
    id: 2,
    teacher: "Robert",
    imageSrc: "/courses/course-2.jpg",
    teacherProfile: "/HomePageImages/admin-2.png",
    profession:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "149.00",
    no_of_reviews: "6",
    priceBefore: "160.00",
    category: "Featured",
    Duration: "15 hours",
    Lectures: "8",
    Students: "Max 10",
    Video: "10 hours",
    SkillLevel: "Moderate",
    Language: "English",
    subratings: [
      "3",
      "4",
      "5",
      "2",
      "4",
      "4",
      "3",
      "5",
      "4",
      "2"
    ]
  },
  {
    id: 3,
    teacher: "Kristopher",
    imageSrc: "/courses/course-3.jpg",
    teacherProfile: "/HomePageImages/admin-3.png",
    profession:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "120.00",
    no_of_reviews: "18",
    priceBefore: "150.00",
    category: "Featured",
    Duration: "10 hours",
    Lectures: "7",
    Students: "Max 6",
    Video: "7 hours",
    SkillLevel: "Advanced",
    Language: "Hinglish",
    subratings: [
      "4",
      "4",
      "5",
      "3",
      "2",
      "4",
      "3",
      "4",
      "4",
      "3",
      "5",
      "4",
      "4"
    ]
  },
  {
    id: 4,
    teacher: "Aaron Powell",
    imageSrc: "/courses/course-4.jpg",
    teacherProfile: "/HomePageImages/admin-4.png",
    courseDetail:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "49.00",
    no_of_reviews: "9",
    priceBefore: "60.00",
    category: "Featured",
    Duration: "12 hours",
    Lectures: "5",
    Students: "Max 6",
    Video: "10 hours",
    SkillLevel: "Easy",
    Language: "Hindi",
    subratings: [
      "5",
      "3",
      "4",
      "3",
      "4",
      "3",
      "4",
      "3",
      "4"
    ]
  },
  {
    id: 5,
    teacher: "Robert",
    imageSrc: "/courses/course-5.jpg",
    teacherProfile: "/HomePageImages/admin-5.png",
    profession:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "149.00",
    no_of_reviews: "10",
    priceBefore: "60.00",
    category: "Featured",
    Duration: "10 hours",
    Lectures: "6",
    Students: "Max 6",
    Video: "8 hours",
    SkillLevel: "Moderate",
    Language: "French",
    subratings: [
      "3",
      "4",
      "3",
      "2",
      "5",
      "4",
      "3",
      "4",
      "3",
      "2"
    ]
  },
  {
    id: 6,
    teacher: "Kristopher",
    imageSrc: "/courses/course-6.jpg",
    teacherProfile: "/HomePageImages/admin-6.png",
    profession:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "120.00",
    no_of_reviews: "13",
    priceBefore: "150.00",
    category: "Featured",
    Duration: "5 hours",
    Lectures: "3",
    Students: "Max 15",
    Video: "3 hours",
    SkillLevel: "Easy",
    Language: "Hindi",
    subratings: [
      "4",
      "4",
      "5",
      "3",
      "4",
      "4",
      "3",
      "4",
      "5"
    ]
  },
  {
    id: 7,
    teacher: "Aaron Powell",
    imageSrc: "/courses/course-7.jpg",
    teacherProfile: "/HomePageImages/admin-1.png",
    courseDetail:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "49.00",
    no_of_reviews: "2",
    priceBefore: "60.00",
    category: "Business",
    Duration: "10 hours",
    Lectures: "6",
    Students: "Max 6",
    Video: "8 hours",
    SkillLevel: "Advanced",
    Language: "Hinglish",
    subratings: [
      "2",
      "3"
    ]
  },
  {
    id: 8,
    teacher: "Robert",
    imageSrc: "/courses/course-8.jpg",
    teacherProfile: "/HomePageImages/admin-2.png",
    profession:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "149.00",
    no_of_reviews: "29",
    priceBefore: "160.00",
    category: "Business",
    Duration: "12 hours",
    Lectures: "5",
    Students: "Max 6",
    Video: "10 hours",
    SkillLevel: "Easy",
    Language: "English",
    subratings: [
      "4",
      "5",
      "3",
      "4",
      "4",
      "5",
      "4",
      "3",
      "4",
      "5",
      "4",
      "3",
      "5",
      "4",
      "5",
      "3",
      "4",
      "5",
      "3",
      "4",
      "5",
      "4",
      "3"
    ]
  },
  {
    id: 9,
    teacher: "Kristopher",
    imageSrc: "/courses/course-9.jpg",
    teacherProfile: "/HomePageImages/admin-3.png",
    profession:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "120.00",
    no_of_reviews: "32",
    priceBefore: "150.00",
    category: "Business",
    Duration: "19 hours",
    Lectures: "9",
    Students: "Max 10",
    Video: "10 hours",
    SkillLevel: "Moderate",
    Language: "English",
    subratings: [
      "5",
      "4",
      "4",
      "5",
      "4",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4"
    ]
  },
  {
    id: 10,
    teacher: "Aaron Powell",
    imageSrc: "/courses/course-1.jpg",
    teacherProfile: "/HomePageImages/admin-4.png",
    courseDetail:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "49.00",
    no_of_reviews: "14",
    priceBefore: "60.00",
    category: "Business",
    Duration: "12 hours",
    Lectures: "5",
    Students: "Max 6",
    Video: "10 hours",
    SkillLevel: "Easy",
    Language: "French",
    subratings: [
      "3",
      "4",
      "5",
      "4",
      "3",
      "5",
      "4",
      "3",
      "5",
      "4",
      "4",
      "5",
      "3",
      "4"
    ]
  },
  {
    id: 11,
    teacher: "Robert",
    imageSrc: "/courses/course-2.jpg",
    teacherProfile: "/HomePageImages/admin-5.png",
    profession:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "149.00",
    no_of_reviews: "1",
    priceBefore: "60.00",
    category: "Photography",
    Duration: "15 hours",
    Lectures: "8",
    Students: "Max 10",
    Video: "10 hours",
    SkillLevel: "Advance",
    Language: "English",
    subratings: [
      "1"
    ]
  },
  {
    id: 12,
    teacher: "Kristopher",
    imageSrc: "/courses/course-3.jpg",
    teacherProfile: "/HomePageImages/admin-6.png",
    profession:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "120.00",
    no_of_reviews: "38",
    priceBefore: "150.00",
    category: "Photography",
    Duration: "15 hours",
    Lectures: "8",
    Students: "Max 10",
    Video: "10 hours",
    SkillLevel: "Moderate",
    Language: "Hindi",
    subratings: [
      "5",
      "4",
      "3",
      "5",
      "4",
      "4",
      "5",
      "3",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "3",
      "4",
      "4",
      "5"
    ]
  },
  {
    id: 13,
    teacher: "Aaron Powell",
    imageSrc: "/courses/course-4.jpg",
    teacherProfile: "/HomePageImages/admin-1.png",
    courseDetail:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "49.00",
    no_of_reviews: "25",
    priceBefore: "60.00",
    category: "Photography",
    Duration: "15 hours",
    Lectures: "8",
    Students: "Max 10",
    Video: "10 hours",
    SkillLevel: "Easy",
    Language: "Hinglish",
    subratings: [
      "4",
      "5",
      "3",
      "4",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "3",
      "4",
      "4",
      "5",
      "4",
      "5",
      "3",
      "4",
      "4",
      "5",
      "4",
      "5",
      "3",
      "4",
      "5",
      "4",
      "5"
    ]
  },
  {
    id: 14,
    teacher: "Robert",
    imageSrc: "/courses/course-5.jpg",
    teacherProfile: "/HomePageImages/admin-2.png",
    profession:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "149.00",
    no_of_reviews: "30",
    priceBefore: "160.00",
    category: "Photography",
    Duration: "15 hours",
    Lectures: "8",
    Students: "Max 10",
    Video: "10 hours",
    SkillLevel: "Moderate",
    Language: "English",
    subratings: [
      "4",
      "5",
      "4",
      "3",
      "5",
      "4",
      "5",
      "3",
      "4",
      "5",
      "4",
      "3",
      "4",
      "5",
      "4",
      "5",
      "3",
      "4",
      "4",
      "5",
      "3",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "3",
      "4",
      "5"
    ]
  },
  {
    id: 15,
    teacher: "Kristopher",
    imageSrc: "/courses/course-6.jpg",
    teacherProfile: "/HomePageImages/admin-3.png",
    profession:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "120.00",
    no_of_reviews: "28",
    priceBefore: "150.00",
    category: "Development",
    Duration: "15 hours",
    Lectures: "8",
    Students: "Max 10",
    Video: "10 hours",
    SkillLevel: "Moderate",
    Language: "French",
    subratings: [
      "5",
      "4",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "3",
      "4",
      "5",
      "4",
      "5",
      "3",
      "4",
      "5",
      "3",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "3",
      "4",
      "5"
    ]
  },
  {
    id: 16,
    teacher: "Aaron Powell",
    imageSrc: "/courses/course-7.jpg",
    teacherProfile: "/HomePageImages/admin-4.png",
    courseDetail:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "49.00",
    no_of_reviews: "4",
    priceBefore: "60.00",
    category: "Development",
    Duration: "15 hours",
    Lectures: "8",
    Students: "Max 10",
    Video: "10 hours",
    SkillLevel: "Easy",
    Language: "Hindi",
    subratings: [
      "4",
      "3",
      "5",
      "3"
    ]
  },
  {
    id: 17,
    teacher: "Robert",
    imageSrc: "/courses/course-8.jpg",
    teacherProfile: "/HomePageImages/admin-5.png",
    profession:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "149.00",
    no_of_reviews: "22",
    priceBefore: "160.00",
    category: "Development",
    Duration: "15 hours",
    Lectures: "8",
    Students: "Max 10",
    Video: "10 hours",
    SkillLevel: "Advance",
    Language: "Hinglish",
    subratings: [
      "5",
      "4",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "3",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4"
    ]
  },
  {
    id: 18,
    teacher: "Kristopher",
    imageSrc: "/courses/course-9.jpg",
    teacherProfile: "/HomePageImages/admin-6.png",
    profession:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "120.00",
    no_of_reviews: "17",
    priceBefore: "150.00",
    category: "Development",
    Duration: "15 hours",
    Lectures: "8",
    Students: "Max 10",
    Video: "10 hours",
    SkillLevel: "Moderate",
    Language: "French",
    subratings: [
      "4",
      "3",
      "5",
      "4",
      "5",
      "4",
      "5",
      "3",
      "4",
      "5",
      "4",
      "5",
      "4",
      "3",
      "5",
      "4",
      "3"
    ]
  },
  {
    id: 19,
    teacher: "Aaron Powell",
    imageSrc: "/courses/course-1.jpg",
    teacherProfile: "/HomePageImages/admin-1.png",
    courseDetail:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "49.00",
    no_of_reviews: "23",
    priceBefore: "60.00",
    category: "Development",
    Duration: "15 hours",
    Lectures: "8",
    Students: "Max 10",
    Video: "10 hours",
    SkillLevel: "Moderate",
    Language: "Hinglish",
    subratings: [
      "5",
      "4",
      "4",
      "5",
      "3",
      "4",
      "5",
      "4",
      "3",
      "4",
      "5",
      "3",
      "4",
      "5",
      "4",
      "5",
      "3",
      "4",
      "5",
      "4",
      "5",
      "3"
    ]
  },
  {
    id: 20,
    teacher: "Robert",
    imageSrc: "/courses/course-2.jpg",
    teacherProfile: "/HomePageImages/admin-2.png",
    profession:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "149.00",
    no_of_reviews: "8",
    priceBefore: "160.00",
    category: "Development",
    Duration: "15 hours",
    Lectures: "8",
    Students: "Max 10",
    Video: "10 hours",
    SkillLevel: "Easy",
    Language: "English",
    subratings: [
      "4",
      "5",
      "3",
      "4",
      "5",
      "4",
      "5",
      "4"
    ]
  },

  {
    id: 21,
    teacher: "Kristopher",
    imageSrc: "/courses/course-3.jpg",
    teacherProfile: "/HomePageImages/admin-3.png",
    profession:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "120.00",
    no_of_reviews: "12",
    priceBefore: "160.00",
    category: "Featured",
    Duration: "15 hours",
    Lectures: "8",
    Students: "Max 10",
    Video: "10 hours",
    SkillLevel: "Moderate",
    Language: "Hindi",
    subratings: [
      "4",
      "3",
      "5",
      "4",
      "4",
      "5",
      "3",
      "4",
      "5",
      "4",
      "3",
      "5"
    ]
  },
  {
    id: 22,
    teacher: "Aaron Powell",
    imageSrc: "/courses/course-4.jpg",
    teacherProfile: "/HomePageImages/admin-4.png",
    courseDetail:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "49.00",
    no_of_reviews: "17",
    priceBefore: "60.00",
    category: "Business",
    Duration: "15 hours",
    Lectures: "8",
    Students: "Max 10",
    Video: "10 hours",
    SkillLevel: "Advanced",
    Language: "Hinglish",
    subratings: [
      "4",
      "5",
      "4",
      "3",
      "4",
      "5",
      "4",
      "5",
      "4",
      "5",
      "4",
      "3",
      "5",
      "4",
      "3",
      "4",
      "5"
    ]
  },
  {
    id: 23,
    teacher: "Robert",
    imageSrc: "/courses/course-5.jpg",
    teacherProfile: "/HomePageImages/admin-5.png",
    profession:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "149.00",
    no_of_reviews: "20",
    priceBefore: "160.00",
    category: "Business",
    Duration: "15 hours",
    Lectures: "8",
    Students: "Max 10",
    Video: "10 hours",
    SkillLevel: "Moderate",
    Language: "French",
    subratings: [
      "3",
      "4",
      "5",
      "4",
      "4",
      "5",
      "3",
      "4",
      "5",
      "4",
      "4",
      "5",
      "3",
      "4",
      "5",
      "4",
      "5",
      "4",
      "3",
      "4"
    ]
  },
  {
    id: 24,
    teacher: "Kristopher",
    imageSrc: "/courses/course-6.jpg",
    teacherProfile: "/HomePageImages/admin-6.png",
    profession:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis obcaecati rem doloribus aperiam! Dolores molestiae exercitationem",
    price: "120.00",
    no_of_reviews: "10",
    priceBefore: "160.00",
    category: "Photography",
    Duration: "15 hours",
    Lectures: "8",
    Students: "Max 10",
    Video: "10 hours",
    SkillLevel: "Advanced",
    Language: "English",
    subratings: [
      "4",
      "3",
      "5",
      "5",
      "4",
      "3",
      "5",
      "4",
      "5",
      "3"
    ]
  }
];

